#!/usr/bin/env bash
#
#  saturnd The saturn core server.
#
#
# chkconfig: 345 80 20
# description: saturnd
# processname: saturnd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/saturnd, see below
if [ -f /etc/sysconfig/saturnd ]; then
        . /etc/sysconfig/saturnd
fi

RETVAL=0

prog=saturnd
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/saturnd
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/saturnd}

# saturnd defaults to /usr/bin/saturnd, override with BITCOIND_BIN
saturnd=${BITCOIND_BIN-/usr/bin/saturnd}

# saturnd opts default to -disablewallet, override with BITCOIND_OPTS
saturnd_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $saturnd $saturnd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
